import type { Metadata } from "next";
import "./globals.css";
import { Container, CssBaseline } from "@mui/material";
import Head from "next/head";
import Header from "./header/header";
import Providers from "./providers";
import authenticated from "./auth/actions/authenticated";
import logout from "./auth/logout";
// import ModeSwitch from '@/components/ModeSwitch';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await authenticated();

  return (
    <html lang="en">
      {/* <body
        className={inter.className}
      > */}
      <body>
        <Providers authenticated={isAuthenticated}>
          <CssBaseline />
          {/* <ModeSwitch /> */}
          <Header logout={logout} />
          <Container className={isAuthenticated ? 'mt-10' : ""}>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
